"""Opt-in scale test for long-form video sign+verify.

Measures the end-to-end timing budget for a 10-minute 1080p asset
(or longer when opted into) generated by stream-looping the BBB
trailer fixture. Not run by default -- the fixture generation alone
can take tens of seconds and the sign path is dominated by ffmpeg
encode time which we do not want to pay on every smoke run.

Enable with:

    STARDUSTPROOF_TEST_LONG_VIDEO=1 pytest -v tests/test_long_video_scale.py

Or the hour-long variant:

    STARDUSTPROOF_TEST_LONG_VIDEO=very-long \
        STARDUSTPROOF_TEST_LONG_VIDEO_SECONDS=3600 \
        pytest -v tests/test_long_video_scale.py

Budget knobs (all env var overridable):

  STARDUSTPROOF_TEST_LONG_VIDEO           1 | very-long | <unset>
  STARDUSTPROOF_TEST_LONG_VIDEO_SECONDS   600 (10 min)  -- duration to loop to
  STARDUSTPROOF_TEST_LONG_VIDEO_BUDGET_SECONDS  300     -- sign+verify wall time cap
"""

from __future__ import annotations

import os
import subprocess
import time
from pathlib import Path

import pytest

from stardustproof_cli.cli import cmd_sign


FIXTURES_DIR = Path(__file__).parent / "fixtures"
SOURCE_TRAILER = FIXTURES_DIR / "big-buck-bunny-trailer-1080p.mov"

SMOKE_WM_HEX = "001122334455"

# Re-use the per-test smoke helpers so the CLI pipeline is exercised
# exactly as end users would invoke it.
from tests.test_integration_smoke import (  # noqa: E402
    _build_sign_args,
    _smoke_env,
    _verify_via_cli,
)


def _long_video_mode() -> str:
    return os.environ.get("STARDUSTPROOF_TEST_LONG_VIDEO", "").strip()


def _long_video_seconds() -> int:
    raw = os.environ.get("STARDUSTPROOF_TEST_LONG_VIDEO_SECONDS")
    if raw:
        try:
            return int(raw)
        except ValueError:
            pass
    return 600  # 10 minutes by default


def _long_video_budget_seconds() -> int:
    raw = os.environ.get("STARDUSTPROOF_TEST_LONG_VIDEO_BUDGET_SECONDS")
    if raw:
        try:
            return int(raw)
        except ValueError:
            pass
    # Calibrated from a WSL2 reference run (2026-04-24): total =
    # 293.55s (embed 259.4s + sign 31.0s + verify 2.8s) on a 10-min
    # 1080p stream-looped BBB trailer. Default is max(ceil(observed
    # * 1.5, step=10), 300) = 450s. Override via
    # STARDUSTPROOF_TEST_LONG_VIDEO_BUDGET_SECONDS on slower hardware.
    return 450


@pytest.fixture(scope="module")
def long_video_mov(tmp_path_factory) -> Path:
    """Generate a multi-minute 1080p clip by stream-looping the committed
    BBB trailer. Uses the bundled ffmpeg via ``STARDUSTPROOF_FFMPEG`` or
    the one on ``PATH``. Stream-copy only -- no re-encode -- so the
    fixture generation stays fast (usually <10s for 10 min)."""
    mode = _long_video_mode()
    if not mode:
        pytest.skip("Set STARDUSTPROOF_TEST_LONG_VIDEO=1 to enable long-video scale test")

    ffmpeg = os.environ.get("STARDUSTPROOF_FFMPEG")
    if not ffmpeg:
        # Fall back to PATH.
        import shutil
        ffmpeg = shutil.which("ffmpeg")
    if not ffmpeg:
        pytest.skip("ffmpeg is required for long-video fixture generation")

    if not SOURCE_TRAILER.is_file():
        pytest.skip(f"missing source trailer {SOURCE_TRAILER}")

    seconds = _long_video_seconds()
    out_dir = tmp_path_factory.mktemp("long-video")
    out = out_dir / f"long-{seconds}s.mov"

    # Probe source duration so we only loop as many times as we need.
    # stream_loop=-1 plays it forever; -t caps to our target duration.
    cmd = [
        ffmpeg, "-y", "-hide_banner", "-loglevel", "error",
        "-stream_loop", "-1",
        "-i", str(SOURCE_TRAILER),
        "-c", "copy",
        "-t", str(seconds),
        str(out),
    ]
    t0 = time.perf_counter()
    subprocess.run(cmd, check=True, capture_output=True)
    elapsed = time.perf_counter() - t0
    size_mb = out.stat().st_size / (1024 * 1024)
    print(
        f"[long-video] generated {out.name}: {seconds}s, "
        f"{size_mb:.1f} MB in {elapsed:.2f}s",
        flush=True,
    )
    return out


@pytest.mark.slow
@pytest.mark.integration
def test_sign_verify_long_video(long_video_mov, tmp_path):
    """Sign + blind-verify a 10-minute (or configurable) 1080p clip;
    print structured timings; assert total wall time stays under the
    configured budget.

    This is primarily an observability test -- it captures the
    throughput envelope of the full pipeline on real hardware so
    regressions in any phase (watermark embed, manifest sign,
    blind-extract, c2patool verify) show up as budget overruns.
    """
    mode = _long_video_mode()
    if not mode:
        pytest.skip("Set STARDUSTPROOF_TEST_LONG_VIDEO=1 to enable long-video scale test")
    if mode == "very-long":
        pytest.skip(
            "very-long mode belongs to test_sign_verify_very_long_video -- "
            "this test runs at the default duration only"
        )

    keystore_url, org_uuid, access_token, bin_dir = _smoke_env()

    seconds = _long_video_seconds()
    budget_seconds = _long_video_budget_seconds()
    output_path = tmp_path / f"signed-long-{seconds}s.mov"
    manifest_store = tmp_path / "manifest-store"

    args = _build_sign_args(
        input_path=long_video_mov,
        output_path=output_path,
        manifest_store=manifest_store,
        org_uuid=org_uuid,
        keystore_url=keystore_url,
        access_token=access_token,
        bin_dir=bin_dir,
        wm_payload_hex=SMOKE_WM_HEX,
    )

    t_sign_start = time.perf_counter()
    rc = cmd_sign(args)
    sign_elapsed = time.perf_counter() - t_sign_start
    assert rc == 0
    assert output_path.exists()

    t_verify_start = time.perf_counter()
    result = _verify_via_cli(output_path, manifest_store, SMOKE_WM_HEX, bin_dir)
    verify_elapsed = time.perf_counter() - t_verify_start

    total = sign_elapsed + verify_elapsed
    size_in_mb = long_video_mov.stat().st_size / (1024 * 1024)
    size_out_mb = output_path.stat().st_size / (1024 * 1024)

    print(
        "[long-video scale]\n"
        f"  duration    = {seconds}s\n"
        f"  input size  = {size_in_mb:.1f} MB\n"
        f"  output size = {size_out_mb:.1f} MB\n"
        f"  sign        = {sign_elapsed:.2f}s\n"
        f"  verify      = {verify_elapsed:.2f}s  "
        f"(blind={result.timings.get('blind_extract_s', 0):.2f}s "
        f"c2patool={result.timings.get('c2patool_s', 0):.2f}s)\n"
        f"  total       = {total:.2f}s\n"
        f"  budget      = {budget_seconds}s",
        flush=True,
    )

    assert total <= budget_seconds, (
        f"long-video sign+verify took {total:.1f}s, exceeds budget "
        f"{budget_seconds}s. Set STARDUSTPROOF_TEST_LONG_VIDEO_BUDGET_SECONDS "
        f"to override."
    )


@pytest.mark.slow
@pytest.mark.integration
def test_sign_verify_very_long_video(long_video_mov, tmp_path):
    """60-minute scale variant. Requires an explicit
    ``STARDUSTPROOF_TEST_LONG_VIDEO=very-long`` opt-in on top of the
    regular long-video flag so operators do not accidentally trigger
    an hour-long sign during CI.
    """
    mode = _long_video_mode()
    if mode != "very-long":
        pytest.skip(
            "Set STARDUSTPROOF_TEST_LONG_VIDEO=very-long to enable the "
            "hour-long scale test variant"
        )

    keystore_url, org_uuid, access_token, bin_dir = _smoke_env()

    seconds = _long_video_seconds()
    # Guardrail: very-long mode MUST be paired with a genuinely
    # long fixture (>= 30 min). Otherwise the test silently falls
    # back to the 10-minute default and runs against a clip that
    # validates nothing the 10-minute test does not already cover
    # -- the operator clearly intended the hour-long variant and
    # deserves a loud error, not a silent no-op.
    if seconds < 1800:
        pytest.fail(
            "STARDUSTPROOF_TEST_LONG_VIDEO=very-long requires "
            "STARDUSTPROOF_TEST_LONG_VIDEO_SECONDS >= 1800 "
            f"(got {seconds}). Refusing to run the very-long variant "
            "against a <30-minute fixture -- it would silently validate "
            "nothing meaningful. Set the env var explicitly, e.g. "
            "STARDUSTPROOF_TEST_LONG_VIDEO_SECONDS=3600 for a 60-min run."
        )

    # Default budget for the very-long variant is 1800s (30 min). The
    # 10-min calibration showed sign+verify ran at ~2x real-time
    # (294s wall for 600s content), so a 60-min clip should land
    # around ~1800s. Override on slower hardware.
    budget_seconds = int(
        os.environ.get("STARDUSTPROOF_TEST_LONG_VIDEO_BUDGET_SECONDS", "1800")
    )
    output_path = tmp_path / f"signed-very-long-{seconds}s.mov"
    manifest_store = tmp_path / "manifest-store"

    args = _build_sign_args(
        input_path=long_video_mov,
        output_path=output_path,
        manifest_store=manifest_store,
        org_uuid=org_uuid,
        keystore_url=keystore_url,
        access_token=access_token,
        bin_dir=bin_dir,
        wm_payload_hex=SMOKE_WM_HEX,
    )

    t_sign_start = time.perf_counter()
    rc = cmd_sign(args)
    sign_elapsed = time.perf_counter() - t_sign_start
    assert rc == 0

    t_verify_start = time.perf_counter()
    result = _verify_via_cli(output_path, manifest_store, SMOKE_WM_HEX, bin_dir)
    verify_elapsed = time.perf_counter() - t_verify_start

    total = sign_elapsed + verify_elapsed
    print(
        f"[very-long-video scale] duration={seconds}s "
        f"sign={sign_elapsed:.1f}s verify={verify_elapsed:.1f}s "
        f"total={total:.1f}s budget={budget_seconds}s",
        flush=True,
    )
    assert total <= budget_seconds, (
        f"very-long-video sign+verify took {total:.1f}s, exceeds budget "
        f"{budget_seconds}s"
    )
